name: Self-Service CI/CD

on:
  push:
    branches: [ master ]
  
jobs:
  build-deploy:

    runs-on: ubuntu-latest
    environment:
      name: master

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install 
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Self-Service
        run: |
              aws ssm send-command \
                  --document-name "AWS-RunRemoteScript" \
                  --instance-ids "${{ secrets.EC2_ID }}" \
                  --region=${{ secrets.AWS_REGION }} \
                  --comment "github interaction-self-service" \
                  --parameters '{"sourceType":["GitHub"],"sourceInfo":["{\"owner\":\"rootstock\", \"repository\":\"ask-devops\", \"path\": \"self-service/\",\"tokenInfo\":\"{{ssm-secure:github-token}}\"}"],"commandLine":["deploy-self-service.sh"]}'
